CONFIGDIR=$PWD/CONF/
mkdir $CONFIGDIR
LOGEXT=logguer
LOGDIR=$PWD/LOGS/
mkdir $LOGDIR
LOGSIZE=1048576

ARRIDIR="arribos"
REPODIR="repodir"
ACEPDIR="acepdir"
RECHDIR="rechdir"
MAEDIR="mae"
PROCDIR="Procdir"

export CONFIGDIR LOGEXT LOGDIR LOGSIZE ARRIDIR REPODIR ACEPDIR RECHDIR MAEDIR PROCDIR
