#!/bin/bash

function salir {
	exit
}




CONFDIR='./grupo8/conf'
BINDIR='./grupo8/'
MAEDIR='./grupo8/'
ARRIDIR='./grupo8/'
ACEPDIR='./grupo8/'
RECHDIR='./grupo8/'
REPODIR='./grupo8/'
PROCDIR='./grupo8/'
#LOGDIR/<comando>.LOGEXTCOMPLETA ='./grupo8/'  VER BIEN ESTO

mkdir -p $CONFDIR

#inicializo log -> Instalar_TP.log

#GRABAR_L Inicio de Ejecución
echo 'Inicio de Ejecución'

#GRABAR_L Log del Comando INSTALAR_TP: $CONFDIR/Instalar_TP.log
echo "Log del Comando INSTALAR_TP: $CONFDIR/Instalar_TP.log"

#GRABAR_L "Directorio de Configuración: CONFDIR"
echo "Directorio de Configuración: $CONFDIR"

#Detectar si paquete RESER_B
if [ -f $CONFDIR/Instalar_TP.conf ];
then 
	#---->CARGAR DESDE Instalar_TP.conf LOS PARAMETROS ANTERIORMENTE ELEJIDO
	#---->VER EL TEMA DE CUALES MODULOS FUERON INSTALADOS Y QUE PARAMETROS FUERON CARGADOS
	#---->VER ITEMS 4.1 Y 4.2 PAG 16
	echo "ESTA el archivo, Se asume que parte de la instalacion fue realizada previamente"
	echo ' TP SO7508 Segundo Cuatrimestre 2013. Tema B Copyright © Grupo 8'
	echo " Librería del Sistema: $CONFDIR"
	#echo " ls $CONFDIR"
	echo " Ejecutables: $BINDIR (mostrar path y listar archivos)"
	echo " Archivos maestros: $MAEDIR (mostrar path y listar archivos)"
	echo " Directorio de arribo de archivos externos: $ARRIDIR"
	echo " Archivos externos aceptados: $ACEPDIR"
	echo " Archivos externos rechazados: $RECHDIR"
	echo " Reportes de salida: $REPODIR"
	echo " Archivos procesados: $PROCDIR"
	#echo " Logs de auditoría del Sistema: LOGDIR/<comando>.LOGEXT" VER BIEN ESTO
	echo " Estado de la instalación: COMPLETA"
	echo " Proceso de Instalación Cancelado"
else
	echo 'Instalación por PRIMERA vez'
	echo 'TP SO7508 Segundo Cuatrimestre 2013. Tema B Copyright © Grupo 8'
	echo 'A T E N C I O N: Al instalar TP SO7508 Segundo Cuatrimestre 2013 UD. expresa aceptar los términos y Condiciones del "ACUERDO DE LICENCIA DE SOFTWARE" incluido en este paquete.'
	echo 'Acepta? Si – No'
	correct='NO'
	while [ correct != 'OK' ];
	do
		read var1
		if [ "$var1" == 'Si' ];
			then	echo 'DIJISTE SI'
				$correct='OK'
		elif [ "$var1" == "No" ];
			then	echo 'DIJISTE NOO'
			salir
		fi
	done
	
	#creo archivo Instalar_TP.conf

fi

